name: Deploy to Trigger.dev (self-hosted)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      # docker setup - part 1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # docker setup - part 2 (GHCR login)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🚀 Deploy Trigger.dev
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
          # required when self-hosting
          TRIGGER_API_URL: ${{ secrets.TRIGGER_API_URL }}
          TRIGGER_SERVER_URL: ${{ secrets.TRIGGER_API_URL }
        run: |
          sed -i 's|proj_fyeypkhgyaejpiweobwq|proj_ojornoedwjbzoigcdkcn|g' ./src/trigger.config.ts
          npx trigger.dev@latest login -a $TRIGGER_SERVER_URL --profile self-hosted
          npx trigger.dev@latest deploy --env staging --profile self-hosted -c ./src/trigger.config.ts
